name: Deployment -  Reusbale workflow
on: 
  workflow_call:
   outputs:
      APP_INGRESS_URL:
        description: Application Ingress URL
        value: ${{ jobs.reuse-deploy.outputs.APP_INGRESS_URL }}
jobs:
  reuse-deploy: 
    environment:
      name: development
      url: https://${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }}
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Verify Kubernetes
        run: |
          kubectl version
          kubectl config current-context
          kubectl get nodes
          minikube status
      - name: Save Minikube IP
        run: |
          IP=$(minikube ip)
          echo "INGRESS_IP=$IP" >> "$GITHUB_ENV"
          echo "Minikube IP: $IP"
      - name: Replace Tokens
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '${'
          tokenSuffix: '}'
          files: '["kubernetes/development/*.yaml"]'
        env:
          NAMESPACE: ${{ vars.NAMESPACE }}
          REPLICAS: ${{ vars.REPLICAS }}
          K8S_IMAGE: ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
          INGRESS_IP: ${{ env.INGRESS_IP }}
      - name: Check Kubernetes Manifests
        run: |
          cat kubernetes/development/*.yaml
      - name: Create Namespace
        run: |
          kubectl create namespace ${{ vars.NAMESPACE }} \
          --dry-run=client -o yaml | kubectl apply -f -
      - name: Create MongoDB Secret
        run: >
          kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds \

          --from-literal=MONGO_URI="${{ env.MONGO_URI }}" \

          --from-literal=MONGO_USERNAME="${{ vars.MONGO_USERNAME }}" \

          --from-literal=MONGO_PASSWORD="${{ secrets.MONGO_PASSWORD }}" \

          --dry-run=client -o yaml | kubectl apply -f -
      - name: Deploy Application
        run: |
          kubectl apply -f kubernetes/development
      - name: Wait for Deployment
        run: |
          kubectl rollout status deployment/solar-system \
          -n ${{ vars.NAMESPACE }} --timeout=180s
      - name: Verify Resources
        run: |
          kubectl get all -n ${{ vars.NAMESPACE }}
          kubectl get ingress -n ${{ vars.NAMESPACE }}
      - name: Set App Ingress Host
        id: set-ingress-host-address
        run: |
         APP_HOST=$(kubectl -n ${{ vars.NAMESPACE }} get ingress -o jsonpath='{.items[0].spec.rules[0].host}')

         echo "Application Host: $APP_HOST"

         echo "APP_INGRESS_HOST=$APP_HOST" >> $GITHUB_OUTPUT
      - name: Debug Output
        run: |
         echo "Output = ${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }}"
  
