name: Solar System Workflow

on:
  workflow_dispatch:
  push:
    branches:
     - main
     - feature/*

jobs:
  Unit-testing:
      name: Unit Testing
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup NodeJS Version - 18
        uses: action/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run:  npm install

      - name: Unit Testing
        run: npm test
