name: Solar System Workflow

on:
  workflow_dispatch:
  push:
    branches:
     - main
     - feature/*
env: 
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD}}
jobs:
  Unit-Testing:
      name: Unit Testing
      strategy:
          matrix:
              nodejs_version: [18, 20]
              operating_system: [ubuntu-latest]
              exclude:
                  - nodejs_version: 20
                    operating_system: ubuntu-latest
      runs-on: ${{ matrix.operating_system }}
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup NodeJS Version - ${{ matrix.nodejs_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodejs_version }}

      - name: cache NPM Dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashfiles('package-lock.json') }}

      - name: Install Dependencies
        run:  npm install

      - name: Unit Testing
        id: nodejs-unit-testing-step
        run: npm test

      - name: Archive/upload Test Result
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Mocha-Test-Result
          path: test-results.xml
  Code-Coverage:
      needs: Unit-testing
      name: Code Coverage
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup NodeJS Version - 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: cache NPM Dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashfiles('package-lock.json') }}

      - name: Install Dependencies
        run:  npm install

      - name: Check Code Coverage
        continue-on-error: true
        run: npm run coverage

      - name: Archive/upload Test Result
        uses: actions/upload-artifact@v4
        with:
          name: Code-Coverage-Result
          path: coverage
          retention-days: 5
    
  Docker:
      name: Containerization
      needs: [unit-testing, code-coverage]
      permissions:
          # contents: read 
          packages: write
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Dockerhub login 
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: GHCR login 
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Docker Build for testing
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}

      - name: Docker image test
        run: |
           docker images
           docker run --name solar-system-app -d \
           -p 3000:3000 \
           -e MONGO_URI=$MONGO_URI \
           -e MONGO_USERNAME=$MONGO_USERNAME \
           -e MONGO_PASSWORD=$MONGO_PASSWORD \
           ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha}}
           
           export IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-system-app)
           echo $IP
          
           echo Testing Image URI using wget
           wget -q -O - 127.0.0.1:3000/live | grep live 

      - name: Container Registry Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
           ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}    
           ghcr.io/${{ github.repository_owner }}/solar-system:${{ github.sha}}
  dev-deploy:
    needs: [Unit-Testing, Code-Coverage, Docker]
    outputs:
      APP_INGRESS_URL: ${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }}
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # - name: Install kubectl CLI
      #   uses: azure/setup-kubectl@v3
      #   with:
      #     version: 'v1.26.0'

      # - name: Create kubeconfig from GitHub secret
      #   env:
      #     KUBECONFIG_CONTENT: ${{ secrets.KUBECONFIG }}
      #   shell: bash
      #   run: |
          

      - name: Fetch Kubernetes cluster details
        run: |
          kubectl version --client
          Write-Host "-------------------------------"
          kubectl config view --minify
          Write-Host "-------------------------------"
          kubectl get nodes  
      - name: save nginx controller IP as a github enviroment variable
        run: |
          $ip = kubectl -n ingress-nginx get svc ingress-nginx-controller -o jsonpath="{.status.loadBalancer.ingress[0].ip}"
          "INGRESS_IP=$ip" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Replace Token in Manifest Files 
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '${'
          tokensuffix: '}'
          files: '["kubernetes/development/*.yaml"]'
        env:
          NAMESPACE: ${{ vars.NAMESPACE }}
          REPLICAS: ${{ vars.REPLICAS }}
          K8S_IMAGE: ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
          INGRESS_IP: ${{ env.INGRESS_IP }}

      - name: check files
        run: |
          Get-Content kubernetes/development/*.yaml  

      - name: Create namespace
        run: |
          kubectl create namespace ${{ vars.NAMESPACE }} --dry-run=client -o yaml | kubectl apply -f -

      - name: Create MongoDB secret
        run: |
          kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds `
          --from-literal=MONGO_URI=${{ env.MONGO_URI }} `
          --from-literal=MONGO_USERNAME=${{ vars.MONGO_USERNAME }} `
          --from-literal=MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} `
          --save-config `
          --dry-run=client `
          -o yaml | kubectl apply -f -

      - name : Deploy to Dev Environment 
        run: |
          kubectl apply -f kubernetes/development  

      - name: Set App Ingress Host URL
        id: set-ingress-host-address
        run: |
         $ingressHost = kubectl -n ${{ vars.NAMESPACE }} get ingress -o jsonpath="{.items[0].spec.tls[0].hosts[0]}"
         Write-Host "Host: '$ingressHost'"
         "APP_INGRESS_HOST=$ingressHost" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

  Integration-Test:
     name: Dev Integration Testing
     needs: dev-deploy
     runs-on: self-hosted

     steps:
     - name: Test URL Output
       env: 
        URL: ${{ needs.dev-deploy.outputs.APP_INGRESS_URL }}
       run: |
        Write-Host $env:URL
        Write-Host "-------------------------------"

        $response = Invoke-RestMethod -Uri "http://$env:URL/live"

        Write-Host $response.status

        if ($response.status -ne "live") {
          throw "Application is not live."
        }